# Generated by Django 4.1.1 on 2022-09-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128, verbose_name='Nom Complet')),
                ('tel', models.CharField(max_length=128, verbose_name='Téléphone')),
                ('email', models.CharField(max_length=128, verbose_name='E-mail')),
            ],
        ),
    ]
